name: CICD with github actions

on:
  workflow_run:
    workflows: Build and push Odoo image
    types: completed 

jobs:
  deploy:
    runs-on: self-hosted
    steps:
       - name: Login to AWS EC2 instance
         uses: ubuntu/aws-ec2-ssh@v1.4.0
         with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          instance-id: ${{ secrets.EC2_INSTANCE_ID }}
          user: ubuntu  # Adjust username if needed
          pem-key-file: ${{ secrets.SSH_KEY }}

       - name: Pull Latest Changes
         run: git pull origin main
       - name: Restart Odoo Service
         run: |
          sudo service odoo-server start
