name: CICD with github actions

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run whoami
        run: |
          echo "Current user (triggering the workflow): ${{ github.actor }}"
          whoami

      - name: Change directory permissions (adjust permissions as needed)
        run: chmod -R 755 /opt/odoo/custom/odoo-CICD/addons

      - name: Change the directory (after permission change)
        run: cd /opt/odoo/custom/odoo-CICD/addons
  
      - name: Pull Latest Changes
        run: git pull origin main

      # - name: Start Odoo service (on EC2)
      #   run: sudo systemctl start odoo
