name: CICD with github actions

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: self-hosted
    steps:
       - name: Checkout code
         uses: actions/checkout@v2  
       
       - name: Pull Latest Changes
         run: git pull origin main

       - name: change the directory
         run: cd /opt/odoo/custom/odoo-CICD/addons
       
       - name: Start Odoo service (on EC2)
         run: sudo systemctl start odoo
